### ISSUE TITLE
Remove the node_modules Folder

### ISSUE THREAD

**Issue by cozerCode** [TheDuckDev/DirectShare#8]
it's just useless
we can just `npm install` inside the `package.json` directory

just put the folder in `.gitignore`

**Comment by aryanbaburajan** [comment]
Makes sense, alright I'll do it later.
I mean I was planning on rewriting this to be better soon, so yeah xd

**Comment by cozerCode** [comment]
closed

**Comment by cozerCode** [comment]
re-opened cuz you forgot about deleting the node_modules folder

**Comment by cozerCode** [comment]
I'm dying
